using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend_api.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Rates",
                columns: table => new
                {
                    GEOCODE = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    ZIP = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    STATE_NAME = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    STATE_SALES_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_MINIMUM1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_MAXIMUM1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_SPLIT_AMOUNT1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SPLIT_SALES_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_MAX_TAX_AMOUNT1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_RATE2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_MINIMUM2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_MAXIMUM2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_SPLIT_AMOUNT2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_SPLIT_RATE2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_MAX_TAX_AMOUNT2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_RATE3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_MINIMUM3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_MAXIMUM3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_SPLIT_AMOUNT3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_SPLIT_RATE3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SALES_MAX_TAX_AMOUNT3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_MINIMUM1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_MAXIMUM1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_SPLIT_AMOUNT1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_SPLIT_USE_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_MAX_TAX_AMOUNT1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_RATE2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_MINIMUM2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_MAXIMUM2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_SPLIT_AMOUNT2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_SPLIT_RATE2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_MAX_TAX_AMOUNT2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_RATE3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_MINIMUM3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_MAXIMUM3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_SPLIT_AMOUNT3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_SPLIT_RATE3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STATE_USE_MAX_TAX_AMOUNT3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_NAME = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    COUNTY_SALES_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_MINIMUM1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_MAXIMUM1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_SPLIT_AMOUNT1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SPLIT_SALES_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_MAX_TAX_AMOUNT1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_RATE2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_MINIMUM2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_MAXIMUM2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_SPLIT_AMOUNT2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_SPLIT_RATE2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_MAX_TAX_AMOUNT2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_RATE3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_MINIMUM3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_MAXIMUM3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_SPLIT_AMOUNT3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_SPLIT_RATE3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SALES_MAX_TAX_AMOUNT3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_MINIMUM1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_MAXIMUM1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_SPLIT_AMOUNT1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_SPLIT_USE_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_MAX_TAX_AMOUNT1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_RATE2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_MINIMUM2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_MAXIMUM2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_SPLIT_AMOUNT2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_SPLIT_RATE2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_MAX_TAX_AMOUNT2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_RATE3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_MINIMUM3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_MAXIMUM3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_SPLIT_AMOUNT3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_SPLIT_RATE3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COUNTY_USE_MAX_TAX_AMOUNT3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_NAME = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CITY_SALES_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_MINIMUM1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_MAXIMUM1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_SPLIT_AMOUNT1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SPLIT_SALES_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_MAX_TAX_AMOUNT1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_RATE2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_MINIMUM2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_MAXIMUM2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_SPLIT_AMOUNT2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_SPLIT_RATE2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_MAX_TAX_AMOUNT2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_RATE3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_MINIMUM3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_MAXIMUM3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_SPLIT_AMOUNT3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_SPLIT_RATE3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SALES_MAX_TAX_AMOUNT3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_MINIMUM1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_MAXIMUM1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_SPLIT_AMOUNT1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_SPLIT_USE_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_MAX_TAX_AMOUNT1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_RATE2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_MINIMUM2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_MAXIMUM2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_SPLIT_AMOUNT2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_SPLIT_RATE2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_MAX_TAX_AMOUNT2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_RATE3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_MINIMUM3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_MAXIMUM3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_SPLIT_AMOUNT3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_SPLIT_RATE3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CITY_USE_MAX_TAX_AMOUNT3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STJ1_NAME = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    STJ1_SALES_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STJ1_USE_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STJ2_NAME = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    STJ2_SALES_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STJ2_USE_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STJ3_NAME = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    STJ3_SALES_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STJ3_USE_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STJ4_NAME = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    STJ4_SALES_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STJ4_USE_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STJ5_NAME = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    STJ5_SALES_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    STJ5_USE_RATE1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COMBINED_SALES_TAX_RATE = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    COMBINED_USE_TAX_RATE = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SD_CODE = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    DEFAULT_CITY = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    EFFECTIVE_DATE = table.Column<DateTime>(type: "datetime2", nullable: true),
                    HISTORY_FLAG = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    STATE_TAX_AUTHORITY = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    COUNTY_TAX_AUTHORITY = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    CITY_TAX_AUTHORITY = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    STJ1_TAX_AUTHORITY = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    STJ2_TAX_AUTHORITY = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    STJ3_TAX_AUTHORITY = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    STJ4_TAX_AUTHORITY = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    STJ5_TAX_AUTHORITY = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    UNINCORPORATED_AREA = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    MAILING_ADDRESS = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                    VERTICAL = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    REPORTING_CITY = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    STJ1_CITY_CNTY_FLAG = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    STJ2_CITY_CNTY_FLAG = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    STJ3_CITY_CNTY_FLAG = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    STJ4_CITY_CNTY_FLAG = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    STJ5_CITY_CNTY_FLAG = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Rates", x => x.GEOCODE);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Rates");
        }
    }
}
