// <auto-generated />
using System;
using BackendApi.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Models.Rate", b =>
                {
                    b.Property<string>("GEOCODE")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CITY_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CITY_SALES_MAXIMUM1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_MAXIMUM2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_MAXIMUM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_MAX_TAX_AMOUNT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_MAX_TAX_AMOUNT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_MAX_TAX_AMOUNT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_MINIMUM1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_MINIMUM2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_MINIMUM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_RATE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_RATE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_SPLIT_AMOUNT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_SPLIT_AMOUNT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_SPLIT_AMOUNT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_SPLIT_RATE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SALES_SPLIT_RATE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SPLIT_SALES_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_SPLIT_USE_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CITY_TAX_AUTHORITY")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("CITY_USE_MAXIMUM1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_MAXIMUM2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_MAXIMUM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_MAX_TAX_AMOUNT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_MAX_TAX_AMOUNT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_MAX_TAX_AMOUNT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_MINIMUM1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_MINIMUM2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_MINIMUM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_RATE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_RATE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_SPLIT_AMOUNT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_SPLIT_AMOUNT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_SPLIT_AMOUNT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_SPLIT_RATE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CITY_USE_SPLIT_RATE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COMBINED_SALES_TAX_RATE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COMBINED_USE_TAX_RATE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("COUNTY_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("COUNTY_SALES_MAXIMUM1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_MAXIMUM2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_MAXIMUM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_MAX_TAX_AMOUNT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_MAX_TAX_AMOUNT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_MAX_TAX_AMOUNT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_MINIMUM1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_MINIMUM2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_MINIMUM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_RATE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_RATE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_SPLIT_AMOUNT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_SPLIT_AMOUNT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_SPLIT_AMOUNT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_SPLIT_RATE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SALES_SPLIT_RATE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SPLIT_SALES_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_SPLIT_USE_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("COUNTY_TAX_AUTHORITY")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("COUNTY_USE_MAXIMUM1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_MAXIMUM2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_MAXIMUM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_MAX_TAX_AMOUNT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_MAX_TAX_AMOUNT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_MAX_TAX_AMOUNT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_MINIMUM1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_MINIMUM2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_MINIMUM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_RATE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_RATE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_SPLIT_AMOUNT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_SPLIT_AMOUNT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_SPLIT_AMOUNT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_SPLIT_RATE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COUNTY_USE_SPLIT_RATE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DEFAULT_CITY")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EFFECTIVE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("HISTORY_FLAG")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MAILING_ADDRESS")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("REPORTING_CITY")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SD_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("STATE_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("STATE_SALES_MAXIMUM1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_MAXIMUM2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_MAXIMUM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_MAX_TAX_AMOUNT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_MAX_TAX_AMOUNT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_MAX_TAX_AMOUNT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_MINIMUM1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_MINIMUM2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_MINIMUM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_RATE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_RATE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_SPLIT_AMOUNT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_SPLIT_AMOUNT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_SPLIT_AMOUNT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_SPLIT_RATE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SALES_SPLIT_RATE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SPLIT_SALES_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_SPLIT_USE_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STATE_TAX_AUTHORITY")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("STATE_USE_MAXIMUM1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_MAXIMUM2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_MAXIMUM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_MAX_TAX_AMOUNT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_MAX_TAX_AMOUNT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_MAX_TAX_AMOUNT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_MINIMUM1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_MINIMUM2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_MINIMUM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_RATE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_RATE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_SPLIT_AMOUNT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_SPLIT_AMOUNT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_SPLIT_AMOUNT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_SPLIT_RATE2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("STATE_USE_SPLIT_RATE3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STJ1_CITY_CNTY_FLAG")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("STJ1_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("STJ1_SALES_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STJ1_TAX_AUTHORITY")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("STJ1_USE_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STJ2_CITY_CNTY_FLAG")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("STJ2_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("STJ2_SALES_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STJ2_TAX_AUTHORITY")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("STJ2_USE_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STJ3_CITY_CNTY_FLAG")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("STJ3_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("STJ3_SALES_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STJ3_TAX_AUTHORITY")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("STJ3_USE_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STJ4_CITY_CNTY_FLAG")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("STJ4_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("STJ4_SALES_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STJ4_TAX_AUTHORITY")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("STJ4_USE_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STJ5_CITY_CNTY_FLAG")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("STJ5_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("STJ5_SALES_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STJ5_TAX_AUTHORITY")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("STJ5_USE_RATE1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UNINCORPORATED_AREA")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VERTICAL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZIP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("GEOCODE");

                    b.ToTable("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
